name: file_type
version: 2.0.0
description: >-
  Utilities for handling media (MIME) types, including determining a type from
  a file extension and file contents.
repository: https://github.com/hossameldinmi/file-type.git

topics:
  - magic-numbers
  - mime
  - mimetype
  - multipart-form
  - file-extensions
  - file-type
  - media-type

environment:
  sdk: ^3.2.0

dependencies:
  equatable: ^2.0.7
  mime: ^2.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
