name: file_type_plus
version: 1.0.1
description: >-
  Utilities for handling media (MIME) types, including determining a type from a
  file extension and file contents.
repository: https://github.com/hossameldinmi/file_type_plus.git
topics:
  - mime
  - mimetype
  - file-extensions
  - file-type
  - media-type

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  mime: ^2.0.0

dev_dependencies:
  cross_file: ^0.3.4+2
  dart_flutter_team_lints: ^3.0.0
  test: ^1.26.3
